# Opgelet: altijd een spatie laten na ':'


# Uurrooster:
maandag:
  voormiddag: Dr. Luyten
  namiddag: Dr. Nys
  avond: Dr. Goetghebuer <br> Dr. Nys
dinsdag:
  voormiddag: Dr. Goetghebuer
  namiddag: Dr. Luyten <br> Dr. Nys
  avond: Dr. Luyten <br> Dr. Nys
woensdag:
  voormiddag: Dr. Luyten enkel even weken  <br> Dr. Goetghebuer om de 2 weken
  namiddag: Dr. Luyten of Dr. Goetghebuer <br> Dr. Nys, afwisselend
  avond: Dr. Luyten of Dr. Goetghebuer <br> Dr. Nys, afwisselend
donderdag:
  voormiddag: Dr. Goetghebuer
  namiddag: Dr. Luyten <br> Dr. Nys
  avond: Dr. Luyten <br> Dr. Nys
vrijdag:
  voormiddag: Dr. Luyten of Dr. Goetghebuer, afwisselend
  namiddag: Dr. Luyten of Dr. Goetghebuer <br> Dr. Nys, afwisselend
  avond: Dr. Luyten of Dr. Goetghebuer <br> Dr. Nys, afwisselend



dokter1:
  voornaam: Frédéric
  achternaam: Goetghebuer
  afbeelding: frederic.jpg

dokter2:
  voornaam: Evy
  achternaam: Luyten
  afbeelding: vierkantevy.jpg

dokter3:
  voornaam: Myriam
  achternaam: Nys
  afbeelding: Nys.jpg
  
dokter4:
  voornaam: Psy. An
  achternaam: Vanhooren
  afbeelding: anvanhoorenvierkant.jpg  


tel: 09/228.47.45
tel-geen-leestekens: +3292284745

straat: Adolf Baeyensstraat 99
plaats: 9040 Sint-Amandsberg

# latitude en longitude voor Google Maps
lat: 51.0548008
lng: 3.7512373


title: Huisartsenpraktijk AB99


# De link tussen aanhalingstekens plaatsen!
afpraak-link: "https://www.mtc-it4.be/patient/index.html#/appointments/multi/bjNkcWkyQmFRMkpDVTRFNndleFgzQUVXOUM5YmFUWU4wbHNlWHF6MnJNSDdDYUFQdWNjdzZNcm82MU9pYk00Uw==/"



































# HIERONDER NIET AANKOMEN
###########################



mettitle: "Dr. Goetghebuer, Dr. Luyten, Huisartsenpraktijk Gent Sint-Amandsberg"
description: "Een afspraak bij Dokter Frédéric Goetghebuer of Dokter Evy Luyten kan telefonisch 09/228.47.45 of online gemaakt worden. Huisarts in Gent en Sint-Amandsberg."
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# Disqus
discus-identifier: mr-brown # add your discus identifier
# Tracker
analytics: # Google Analytics
markdown: kramdown
plugins:
  - jekyll-sitemap
permalink: ':title/'
future: true
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
